name: regular_tasks
description: "This repository contains Flutter Widget tasks"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: any
  cupertino_icons: ^1.0.6
  carousel_slider: any
  google_fonts: any
  assets_audio_player: any
  video_player: any
  chewie: any
  blurrycontainer: any
  async_wallpaper: ^2.0.3
  path_provider: any
  flutter_wallpaper_manager: ^0.0.4
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/backgrounds/
    - assets/audios/
